version: '3'
services:
   mongodb:
      image: 'mongo'
      environment:
         - MONGO_URL=mongodb+srv://myapp:lvs123@instakilogram.miy3gsd.mongodb.net/?retryWrites=true&w=majority
      volumes:
         - data:/data/db

   backend:
      build: ./server
      ports:
         - '3001:3001'
      environment:
         - MONGO_URL=mongodb://mongodb:27017/myapp
      volumes:
         - logs:/app/logs
         - .server:/app
         - /app/node_modules
      depends_on:
         - mongodb

   frontend:
      build: ./client
      ports:
         - '3000:3000'
      depends_on:
         - backend

   mobileapp:
      build: ./mobile
      ports:
         - '19000:19000'
         - '19001:19001'
      depends_on:
         - backend

volumes:
   data:
   logs:
