const data = [
  {
    id: 1,
    name: 'son1',
    postName: 'son123',
    image: require('../images/profil.jpg'),
    postImage: require('../images/portakal.jpg'),
    like: 25,
    comment: 'Xem tất cả 4 bình luận',
    explanation: 'Không có gì như nó có vẻ...',
    time: '1 giờ trước',
    timeStory: '1s',
    islike: false,
  },
  {
    id: 2,
    name: 'nghia',
    postName: 'nghia123',
    image: require('../images/macellan.jpg'),
    postImage: require('../images/fintech.jpeg'),
    like: 360,
    comment: 'Xem tất cả 4 bình luận',
    explanation: 'Hãy đợi xem',
    time: '2 giờ trước',
    timeStory: '53d',
    islike: false,
  },
  {
    id: 3,
    name: 'son123',
    postName: 'Nghia be de',
    image: require('../images/ezgiceylan.jpeg'),
    postImage: require('../images/oje.jpg'),
    like: 120,
    comment: 'Xem tất cả 4 bình luận',
    explanation: 'Móng tay mới của tôi :)',
    time: '3 giờ trước',
    timeStory: '2s',
    islike: false,
  },
  {
    id: 4,
    name: 'catvideos',
    postName: 'catvideos',
    image: require('../images/cat.jpg'),
    postImage: require('../images/catPost.jpg'),
    like: 160,
    comment: 'Xem tất cả 8 bình luận',
    explanation: 'Một con mèo tức giận',
    time: '5 giờ trước',
    timeStory: '3s',
    islike: false,
  },
  {
    id: 5,
    name: 'adu',
    postName: 'adu123',
    image: require('../images/alternatif.png'),
    postImage: require('../images/Afiş.png'),
    like: 220,
    comment: 'Xem tất cả 110 bình luận',
    explanation: 'Hãy đợi xem',
    time: '8 giờ trước',
    timeStory: '6s',
    islike: false,
  },
  {
    id: 6,
    name: 'ád',
    postName: '123',
    image: require('../images/bfy.png'),
    postImage: require('../images/bfyPost.jpg'),
    like: 150,
    comment: 'Xem tất cả 25 bình luận',
    explanation: 'Theo dõi phương tiện chưa bao giờ dễ dàng như thế',
    time: '24 giờ trước',
    timeStory: '24s',
    islike: false,
  },
];
export default data;
