import { StyleSheet } from 'react-native';
import Color from '../../database/Database';

export const styles = StyleSheet.create({
   input: {
      height: 50,
      margin: 12,
      borderWidth: 2,
      borderColor: Color.Orange,
      padding: 10,
      borderRadius: 10,
   },
   inputFocus: {
      height: 50,
      margin: 12,
      borderWidth: 2,
      borderColor: Color.Orange,
      padding: 10,
      borderRadius: 10,
      backgroundColor: Color.White,
   },
   title: {
      color: Color.Black,
      fontSize: 40,
      textAlign: 'center',
      justifyContent: 'center',
      marginVertical: 20,
   },
   tinyLogo: {
      width: 200,
      height: 200,
      borderRadius: 50,
   },
   logo: {
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
   },
   loginBtn: {
      backgroundColor: Color.Yellow,
      height: 50,
      width: 100,
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: Color.Orange,
      borderWidth: 1,
      borderRadius: 10,
   },
   regiterBtn: {
      backgroundColor: Color.Yellow,
      height: 50,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      borderColor: Color.Orange,
      borderWidth: 1,
      borderRadius: 10,
      paddingTop: 30,
   },
   containerRP: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
      backgroundColor: '#f5f5f5',
   },
   inputRP: {
      width: '100%',
      marginBottom: 10,
      paddingHorizontal: 10,
      backgroundColor: 'white',
      height: 50,
      borderWidth: 2,
      borderColor: Color.Orange,
      borderRadius: 10,
   },
   logoRP: {
      paddingVertical: '20%',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 10,
   },
});
