const data3 = [
  {
    video: require('../videos/reels1.mp4'),
    image: require('../images/profil.jpg'),
    user: 'son',
    explanation: 'Kỷ niệm...',
    likes: 852,
    comment: '35',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels2.mp4'),
    image: require('../images/profil5.jpg'),
    user: 'hieu',
    explanation: 'Tôi yêu bạn bè của mình <3',
    likes: 25,
    comment: '14',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels3.mp4'),
    image: require('../images/cat.jpg'),
    user: 'son1',
    explanation: 'Chào buổi sáng!',
    comment: 5,
    likes: 134,
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels4.mp4'),
    image: require('../images/ezgiceylan.jpeg'),
    user: 'hieu2',
    explanation: 'Cuối tuần tuyệt vời!',
    likes: 184,
    comment: '3',
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels5.mp4'),
    image: require('../images/profil6.jpg'),
    user: 'tan3',
    explanation: 'Điện thoại mới',
    comment: 55,
    likes: 184,
    isLike: false,
    follow: true,
  },
  {
    video: require('../videos/reels6.mp4'),
    image: require('../images/profil3.jpg'),
    user: 'anbbui',
    explanation: 'VR tuyệt vời, bạn ơi...',
    likes: 124,
    comment: '96',
    isLike: false,
    follow: true,
  },
];
export default data3;
